title: "wenchao's website"
author: "Dingwenchao"
description: "凡是发生必有利于我,事与愿违必是另有安排"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page 在主页上显示文章摘录
show_frame: false          # adds a gray frame to the site 为站点添加灰框
show_sidebar: true         # show a sidebar instead of the usual header 显示侧边栏而不是通常的标题
minimal: true             # use a dark header 使用深色标题

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html",title:"Home", icon: home}
  - {file: "README.md", title:"About", icon: address-card}
  - {file: "新概念英语.pdf", title: "English"}

  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "ding18500347267@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/dingwenchao-cmky"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
