title: "wenchao's website"
author: "Dingwenchao"
description: "凡是发生必有利于我\n\n\n事与愿违必是另有安排"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: true         # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html",title:"Home", icon: home}
  - {file: "README.md", title:"About", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ding18500347267@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/dingwenchao-cmky"}
  - {title: Twitter, icon: Twitter, url: "www.youtube.com/watch?v=D8XYDtn2Q7Q&t=817s"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
